######################################################################
# Automatically generated by qmake (3.0) wt. gru 10 17:54:35 2013
######################################################################

TEMPLATE = lib
TARGET = ../../bin/toremove
INCLUDEPATH += .
OBJECTS_DIR = ../../obj
MOC_DIR = ../../moc
QT += qml quick

# Input
HEADERS += cpp_ui.h
SOURCES += cpp_ui.cpp
